version: '3'
services:
  app:
    build:
      context: ./app
    ports:
      - "5001:5001"
    depends_on:
      - search-engine
    #   - postgres

  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    # links:
    #   - app
    # networks:
    #   - nginx_network

  search-engine:
    build: search-engine
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200"]
      interval: 5s
      timeout: 5s
      retries: 30

  # 今回は postgres をサービスとして定義しました。
  postgres:
    image: postgres:12
    # コンテナの名前を指定します。
    container_name: postgres
    # 環境変数を設定します。
    environment:
      - "POSTGRES_USER=${USER}"
      - "POSTGRES_PASSWORD=${PASSWORD}"
      - POSTGRES_DB=mensaku
    # データの永続化
    volumes:
      # postgresディレクトリを/var/lib/postgresql/dataにマウントする
      - postgres:/var/lib/postgresql/data
      - ./postgres/.initdb:/docker-entrypoint-initdb.d
    # ポートの指定（HOST:CONTAINER）
    expose:
      - "5432"
  
  feeder-master-db:
    build:
      context: .
      dockerfile: ./feeder-master-db/Dockerfile
    tty: true
# データの永続化
volumes:
  postgres: